# This file is log2plot.py
# Created by Luke English 2012
#
# log2plot.py takes in a log.csv file generated by
# our implementation of MC-AIXI-CTW, and returns a
# CSV file with lines of the format
#
#          cycle,average_reward
#
# which can then be passed to PGFPlots.

import csv

f = open('log.csv', 'r')
out = open('plot.csv', 'w')
reader = csv.reader(f)

out.write("# ")
for row in reader:
    writing = row[0] + "\t" + row[-1] + "\n"
    out.write(writing)
